return{
["global font scale"]=1,
["colorPalette"]={},
["windowList"]={
  ["main hp bar"]={
    ["x"]=0,
    ["verticalAnchor"]="top",
    ["optionsChanged"]=false,
    ["openEditor"]=false,
    ["newWidgetType"]=4,
    ["hideMenuStates"]={["main menu"]=false,["quick menu"]=false,["team chat"]=false,["ship service menu"]=true,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=3.8599998950958,
    ["displayList"]={
      {
        ["widgetType"]="progressBar",
        ["args"]={
          ["showFullBar"]=false,
          ["barGradient"]={
            {
              0,
              {1,0,0,1,},
              },
            {
              0.5,
              {0.65490196078431,1,1,1,},
              },
            {
              0.79999995231628,
              {0,1,0.65098039215686,1,},
              },
            {
              1,
              {1,1,1,1,},
              },
            },
          ["textColor"]={0,0,0,1,},
          ["progressFunction"]="Player HP",
          },
        },
      },
    ["horizontalAnchor"]="center",
    ["y"]=0,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=100,
    ["textColor"]={1,1,1,1,},
    ["enabled"]=true,
    ["options"]={"NoTitleBar","NoResize","NoMove","NoScrollbar","",},
    ["h"]=10,
    },
  ["tp bar"]={
    ["x"]=0,
    ["verticalAnchor"]="center",
    ["y"]=18,
    ["openEditor"]=false,
    ["newWidgetType"]=4,
    ["hideMenuStates"]={["main menu"]=true,["quick menu"]=true,["team chat"]=false,["ship service menu"]=false,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1,
    ["displayList"]={
      {
        ["widgetType"]="progressBar",
        ["args"]={
          ["showFullBar"]=true,
          ["barGradient"]={
            {
              0,
              {0.50196078431373,0,1,1,},
              },
            {
              0.3299999833107,
              {0.25,0.35294117647059,1,1,},
              },
            {
              0.6599999666214,
              {0,0.70588235294118,1,1,},
              },
            {
              1,
              {1,1,1,1,},
              },
            },
          ["progressFunction"]="Player TP",
          },
        },
      },
    ["horizontalAnchor"]="left",
    ["optionsChanged"]=false,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=10,
    ["textColor"]={1,1,1,1,},
    ["h"]=10,
    ["options"]={"NoTitleBar","NoResize","NoMove","NoScrollbar","",},
    ["enabled"]=true,
    },
  ["buff timer bar"]={
    ["x"]=0,
    ["verticalAnchor"]="bottom",
    ["y"]=0,
    ["openEditor"]=false,
    ["newWidgetType"]=4,
    ["hideMenuStates"]={["main menu"]=true,["quick menu"]=false,["team chat"]=false,["ship service menu"]=false,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1,
    ["displayList"]={
      {
        ["widgetType"]="progressBar",
        ["args"]={
          ["showFullBar"]=true,
          ["barGradient"]={
            {
              0,
              {0.37254901960784,0,0.25098039215686,1,},
              },
            {
              0.3299999833107,
              {0.71764705882353,0.10196078431373,0.3843137254902,1,},
              },
            {
              0.6599999666214,
              {1,0.20392156862745,0.57647058823529,1,},
              },
            {
              0.84999996423721,
              {1,1,1,1,},
              },
            {
              1,
              {1,1,1,1,},
              },
            },
          ["progressFunction"]="Player S/D/J/Z Timer",
          },
        },
      },
    ["horizontalAnchor"]="right",
    ["optionsChanged"]=false,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=10,
    ["textColor"]={1,1,1,1,},
    ["h"]=10,
    ["options"]={"NoTitleBar","NoResize","NoMove","NoScrollbar","",},
    ["enabled"]=true,
    },
  ["xp bar"]={
    ["x"]=0,
    ["verticalAnchor"]="top",
    ["y"]=10.059999465942,
    ["openEditor"]=false,
    ["newWidgetType"]=4,
    ["hideMenuStates"]={["main menu"]=false,["quick menu"]=false,["team chat"]=false,["ship service menu"]=true,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1,
    ["displayList"]={
      {
        ["widgetType"]="progressBar",
        ["args"]={
          ["textColor"]={0,0,0,1,},
          ["overlayFunction"]="Player XP: to Next Level",
          ["barColor"]={1,1,0,1,},
          ["progressFunction"]="Player XP: Level Progress",
          },
        },
      },
    ["horizontalAnchor"]="center",
    ["optionsChanged"]=false,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=23.479999542236,
    ["textColor"]={1,1,1,1,},
    ["h"]=2,
    ["options"]={"NoTitleBar","NoResize","NoMove","NoScrollbar","",},
    ["enabled"]=true,
    },
  ["misc info"]={
    ["x"]=0,
    ["options"]={"NoTitleBar","NoResize","NoMove","NoScrollbar","",},
    ["y"]=10.059999465942,
    ["openEditor"]=false,
    ["newWidgetType"]=2,
    ["hideMenuStates"]={["main menu"]=false,["quick menu"]=false,["team chat"]=false,["ship service menu"]=true,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1.5,
    ["displayList"]={
      {
        ["widgetType"]="showString",
        ["args"]={["text"]="pack | bank | meseta | session | kXP/h | time",},
        },
      {
        ["widgetType"]="Show Composite String",
        ["args"]={
          ["sourceCS"]={
            {"Number of Inventory Slots Free",4,},
            " |  ",
            {"Number of Bank Slots Free",3,},
            " | ",
            {"Player Meseta Carried",6,},
            " | ",
            {"Session Time Elapsed",7,},
            " | ",
            {"kXP/Hour in Dungeon",5,},
            " | ",
            ["functionList"]={"Number of Inventory Slots Free","Number of Bank Slots Free","Player Meseta Carried","Session Time Elapsed","kXP/Hour in Dungeon",},
            ["displayString"]="  30 |  200 |      0",
            ["formatString"]="%4i |  %3i | %6i | %7i | %5i | ",
            },
          },
        },
      },
    ["horizontalAnchor"]="left",
    ["optionsChanged"]=false,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=38.25,
    ["textColor"]={1,1,1,1,},
    ["enabled"]=true,
    ["verticalAnchor"]="top",
    ["h"]=8.1899995803833,
    },
  ["monster list"]={
    ["x"]=0,
    ["options"]={"NoTitleBar","NoResize","NoMove","","",},
    ["optionsChanged"]=false,
    ["openEditor"]=false,
    ["newWidgetType"]=3,
    ["hideMenuStates"]={["main menu"]=true,["quick menu"]=true,["team chat"]=false,["ship service menu"]=false,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1,
    ["displayList"]={
      {
        ["widgetType"]="show formatted list",
        ["args"]={
          ["format table"]={
            ["field list"]={"name","hp","hpMax",},
            ["field combo list"]={"hp","hpMax","statusFrozen","statusConfused","statusParalyzed","defTech","atkTech","name",["defTech"]=6,["atkTech"]=7,["statusConfused"]=4,["statusParalyzed"]=5,["hpMax"]=2,["hp"]=1,["name"]=8,["statusFrozen"]=3,},
            ["format data"]={
              {"name",0,},
              " ",
              {"hp",0,},
              "/",
              {"hpMax",0,},
              ["format string"]="%0s %0s/%0s",
              },
            ["list source function"]="Monsters in Current Room",
            },
          },
        },
      },
    ["horizontalAnchor"]="right",
    ["y"]=0,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=20,
    ["textColor"]={1,1,1,1,},
    ["enabled"]=true,
    ["verticalAnchor"]="bottom",
    ["h"]=24.85000038147,
    },
  ["floor list"]={
    ["x"]=0,
    ["options"]={"NoTitleBar","NoResize","NoMove","","",},
    ["optionsChanged"]=false,
    ["openEditor"]=false,
    ["newWidgetType"]=3,
    ["hideMenuStates"]={["main menu"]=true,["quick menu"]=true,["team chat"]=false,["ship service menu"]=false,["any menu"]=false,},
    ["hideField"]=true,
    ["fontScale"]=1,
    ["displayList"]={
      {
        ["widgetType"]="show formatted list",
        ["args"]={
          ["format table"]={
            ["subtype edit index"]="weapon",
            ["subtype combo list"]={"barrier","frame","mag","meseta","technique disk","tool","unit","weapon",["unit"]=7,["frame"]=2,["mag"]=3,["barrier"]=1,["tool"]=6,["meseta"]=4,["technique disk"]=5,["weapon"]=8,},
            ["sub format table"]={
              ["mag"]={
                {"index",2,},
                "> ",
                {"color",8,},
                " ",
                {"name",8,},
                " ",
                {"def",2,},
                "d/",
                {"pow",2,},
                "p/",
                {"dex",2,},
                "d/",
                {"mind",2,},
                "m| sync:",
                {"sync",3,},
                " |iq: ",
                {"iq",3,},
                ["format string"]="%2s> %8s %8s %2sd/%2sp/%2sd/%2sm| sync:%3s |iq: %3s",
                },
              ["frame"]={
                {"index",2,},
                "> ",
                {"name",0,},
                " ",
                {"slots",0,},
                "s |",
                {"evade",0,},
                "/",
                {"evadeMax",0,},
                "e |",
                {"defense",0,},
                "/",
                {"defenseMax",0,},
                "d",
                ["format string"]="%2s> %0s %0ss |%0s/%0se |%0s/%0sd",
                },
              ["unit"]={
                {"index",2,},
                "> ",
                {"name",0,},
                ["format string"]="%2s> %0s",
                },
              ["barrier"]={
                {"index",2,},
                "> ",
                {"name",0,},
                " ",
                {"evade",0,},
                "/",
                {"evadeMax",0,},
                "e |",
                {"defense",0,},
                "/",
                {"defenseMax",0,},
                "d",
                ["format string"]="%2s> %0s %0s/%0se |%0s/%0sd",
                },
              ["technique disk"]={
                {"index",2,},
                "> ",
                {"name",0,},
                " lv",
                {"techniqueLevel",0,},
                ["format string"]="%2s> %0s lv%0s",
                },
              ["meseta"]={["format string"]="",},
              ["tool"]={
                {"index",2,},
                "> ",
                {"quantity",0,},
                "x ",
                {"name",0,},
                ["format string"]="%2s> %0sx %0s",
                },
              ["weapon"]={
                {"index",2,},
                "> ",
                {"Native",0,},
                "/",
                {"A. Beast",0,},
                "/",
                {"Machine",0,},
                "/",
                {"Dark",0,},
                "|",
                {"Hit",0,},
                " - ",
                {"special",0,},
                " ",
                {"name",0,},
                " +",
                {"grind",0,},
                ["format string"]="%2s> %0s/%0s/%0s/%0s|%0s - %0s %0s +%0s",
                },
              },
            ["list source function"]="Floor Items",
            ["field list"]={"index","Native","A. Beast","Machine","Dark","Hit","special","name","grind",},
            ["field combo list"]={"index","type","name","grind","wrapped","killcount","untekked","isSrank","SrankName","special","Native","A. Beast","Machine","Dark","Hit",["Hit"]=15,["isSrank"]=8,["wrapped"]=5,["SrankName"]=9,["killcount"]=6,["Machine"]=13,["untekked"]=7,["grind"]=4,["Native"]=11,["special"]=10,["index"]=1,["type"]=2,["A. Beast"]=12,["name"]=3,["Dark"]=14,},
            ["sub field table"]={
              ["mag"]={"index","color","name","def","pow","dex","mind","sync","iq",},
              ["frame"]={"index","name","slots","evade","evadeMax","defense","defenseMax",},
              ["unit"]={"index","name",},
              ["barrier"]={"index","name","evade","evadeMax","defense","defenseMax",},
              ["technique disk"]={"index","name","techniqueLevel",},
              ["meseta"]={},
              ["tool"]={"index","quantity","name",},
              ["weapon"]={"index","Native","A. Beast","Machine","Dark","Hit","special","name","grind",},
              },
            ["format data"]={
              {"index",2,},
              "> ",
              {"Native",0,},
              "/",
              {"A. Beast",0,},
              "/",
              {"Machine",0,},
              "/",
              {"Dark",0,},
              "|",
              {"Hit",0,},
              " - ",
              {"special",0,},
              " ",
              {"name",0,},
              " +",
              {"grind",0,},
              ["format string"]="%2s> %0s/%0s/%0s/%0s|%0s - %0s %0s +%0s",
              },
            },
          },
        },
      },
    ["horizontalAnchor"]="right",
    ["y"]=7.4899997711182,
    ["openOptions"]=false,
    ["transparent"]=false,
    ["w"]=20,
    ["textColor"]={1,1,1,1,},
    ["enabled"]=true,
    ["verticalAnchor"]="center",
    ["h"]=35.329998016357,
    },
  },
["show window list"]=true,
}