return
	{
	['player current hp'] = 'hp',
	['player maximum hp'] = 'maxhp',
	['player current tp'] = 'tp',
	['player maximum tp'] = 'maxtp',
	['invulnerability time'] = 'invuln',
	['player level'] = 'lv',
	['level base xp'] = 'basexp',
	['xp progress'] = 'xp',
	['player ata'] = 'ata',
	['pack meseta'] = 'meseta',
	['session time elapsed'] = 'stime',
	['session xp accumulated'] = 'sxp',
	['session time in dungeon'] = 'dtime',
	['pack slots used'] = 'pitems',
	['pack slots free'] = 'pspace',
	['bank slots used'] = 'bitems',
	['bank slots free'] = 'bspace',
	['bank meseta'] = 'bmoney',
	['hp: current/maximum'] = 'hp/max',
	['tp: current/maximum'] = 'tp/max',
	['xp progress/needed'] = 'xp/nxt',
	['xp to next level'] = 'xp tnl',
	['xp/second this session'] = 'xp/st',
	['kxp/hour this session'] = 'kxp/ht',
	['xp/second in dungeon'] = 'xp/sd',
	['kxp/hour in dungeon'] = 'kxp/hd',
	['pack space: used/total'] = 'pack/m',
	['bank space: used/total'] = 'bank/m',
	['player hp'] = 'hp',
	['player tp'] = 'tp',
	['player deband/zalure timer'] = 'd/z',
	['player shifta/jellen timer'] = 's/j',
	['player s/d/j/z timer'] = 'sdjz',
	} -- return {...}
